site1:
  build: .
  links:
    - site2
  volumes:
    - .:/home/app/corsit
    - ./corsit-bundle:/home/app/bundle
  ports:
    - '8000:80'
  env_file:
    - .env

site2:
  build: .
  volumes:
    - .:/home/app/corsit
    - ./corsit-bundle:/home/app/bundle
  ports:
    - '8001:80'
  env_file:
    - .env
